name: SBWUpgradeSpawner
version: '${project.version}'
main: br.com.impalinha.sbwupgradespawner.Main
api-version: '1.20'
commands:
  sbi:
    description: "Comando principal"
    permission: sbi.admin

