name: SBWUpgradeSpawner
version: '1.0-SNAPSHOT'
main: br.com.impalinha.sbwupgradespawner.Main
api-version: '1.20'
depend: [BedWars]
commands:
  sbi:
    description: "Comando principal"
    permission: sbi.admin

